name: 'Ruby on Rails CI'
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        ports:
          - '33306:3306'
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: rails_test
          MYSQL_USER: rails
          MYSQL_PASSWORD: password
    steps:
      - name: Set up MySQL
        run: |
          sudo service mysql start
          mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
        env:
          DB_DATABASE: rails_test
          DB_USER: rails
          DB_PASSWORD: password
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v3
        with:
          bundler-cache: true
      - name: Set up database schema
        run: bin/rails db:schema:load
        env:
          RAILS_ENV: test
          DATABASE_URL: 'mysql2://rails:password@localhost:3306/rails_test'
      - name: Run tests
        run: bin/rake
        env:
          RAILS_ENV: test
          DATABASE_URL: 'mysql2://rails:password@localhost:3306/rails_test'

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v3
        with:
          bundler-cache: true
      - name: Run bundle install
        run: bundle install
      - name: Security audit dependencies
        run: bundle exec bundler-audit --update
      - name: Lint Ruby files
        run: bundle exec rubocop --parallel
