name: 'Ruby on Rails CI'
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: mysql:latest
        ports:
          - '3306:3306'
        env:
          MYSQL_DATABASE: rails_test
          MYSQL_USER: rails
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_UNIX_PORT: /tmp/mysql.sock
    env:
      RAILS_ENV: test
      DATABASE_URL: 'mysql2://rails:password@localhost:3306/rails_testt?unix_socket=/tmp/mysql.sock'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf
        with:
          bundler-cache: true
      - name: Set up database schema
        run: bin/rails db:schema:load
      - name: Run tests
        run: bin/rake

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf
        with:
          bundler-cache: true
      - name: Run bundle install
        run: bundle install
      - name: Security audit dependencies
        run: bundle exec bundler-audit --update
      - name: Lint Ruby files
        run: bundle exec rubocop --parallel
