name: 'Ruby on Rails CI'
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf
        with:
          bundler-cache: true
      - name: Run bundle install
        run: bundle install
      - name: Security audit dependencies
        run: bundle exec bundler-audit --update
      - name: Lint Ruby files
        run: bundle exec rubocop --parallel
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db
      DATABASE_PORT: 5432
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf
        with:
          bundler-cache: true
      - name: Run bundle install
        run: bundle install
      - name: Security audit dependencies
        run: bundle exec bundler-audit --update
      - name: Install Rails
        run: gem install rails
      - name: Wait for PostgreSQL to be ready
        run: sleep 15 # Give PostgreSQL some time to be fully up
      - name: Create the database
        run: rails db:create
      - name: Setup database schema
        run: rails db:schema:load
      - name: Precompile assets
        run: rails assets:precompile
      - name: Run tests
        run: bin/rspec --format doc
